### ISSUE TITLE
Dual Sim carriers jumping

### ISSUE THREAD

**Issue by purlupar** [pR0Ps/FlatConnectivityIcons#2]
In a Dual Sim phone (samsung j5 2017 duos) the carrier is changing between sim1's and sim2's correcr value. It jumps ca. every 20 seconds.
Both (or either), fixed, would be a nice feature.

Tested on J5 2017 duos aka j530f
Android 7.0
xposed 88.2
This here: 4.0.1

**Comment by pR0Ps** [comment]
Is this a problem with the module or are you proposing adding a fix for behavior you see without the module installed? This module is just a simple image swapper so it shouldn't cause anything like the issue you're describing.

**Comment by purlupar** [comment]
It occurs with this module installed. How is it supposed to behave, then? Sadly Samsung's Android doesn't show any carrier AT ALL any more, that's why I use this module. (Note: I don't use this phone any more so I am reporting from earlier)

**Comment by pR0Ps** [comment]
I don't know how it's supposed to behave in that situation, sorry.

If you can reproduce this issue with the module enabled and can't reproduce it without the module enabled, please feel free to reopen this. As it stands it looks like an issue with the ROM or another module since this module is literally just an image resource swapper.

**Comment by purlupar** [comment]
I can't reproduce it without this module since there are no icons on the native Samsung Android. (to my knowledge). So for me it looks(!) like it is the behavior of this module, since it is it which brings the icon(s) to the notification bar. 
I get your point though I think, so if Samsung OS is it that alternates SIM1 and SIM2 info and this module reads this only, then please close it again.

Edit: I don't know how to reopen this sorry.
